# Generated by Django 6.0.4 on 2026-07-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
