# Generated by Django 6.0.4 on 2026-08-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shipping_address'),
        ('shipping', '0002_shippingcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.shippingaddress'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
