# Generated by Django 6.0.4 on 2026-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_ip_address_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
