# Generated by Django 6.0.4 on 2026-08-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_returnrequestimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
