# Generated by Django 6.0.4 on 2026-09-21 07:11

import apps.orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequestimage',
            name='image',
            field=models.ImageField(upload_to='returns/', validators=[apps.orders.validators.validate_return_image]),
        ),
    ]
