# Generated by Django 6.0.4 on 2026-09-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
