# Generated by Django 6.0.4 on 2026-07-31 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='recentlyviewed',
            name='unique_recently_viewed_product',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_slug_3edc0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_price_9b1a5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_9edb3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_brand_i_dc6890_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_feat_a5d7cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='recentlyviewed',
            name='products_re_user_id_a2acae_idx',
        ),
        migrations.RemoveIndex(
            model_name='recentlyviewed',
            name='products_re_product_1ee2c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='recentlyviewed',
            name='products_re_viewed__099548_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewed',
            unique_together={('user', 'product')},
        ),
    ]
