# Generated by Django 6.0.4 on 2026-07-31 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_flash_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_flash_sale',
        ),
    ]
