# Generated by Django 6.0.4 on 2026-07-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_is_flash_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
