# Generated by Django 6.0.4 on 2026-08-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='WatchStore', max_length=150)),
                ('store_email', models.EmailField(default='admin@watchstore.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='Dhaka, Bangladesh')),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=100)),
                ('store_active', models.BooleanField(default=True)),
                ('new_order_notification', models.BooleanField(default=True)),
                ('new_customer_notification', models.BooleanField(default=True)),
                ('low_stock_notification', models.BooleanField(default=True)),
                ('return_request_notification', models.BooleanField(default=True)),
                ('refund_request_notification', models.BooleanField(default=True)),
                ('email_notification', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('login_alert', models.BooleanField(default=True)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=80, max_digits=10)),
                ('delivery_days', models.PositiveIntegerField(default=5)),
                ('free_shipping_minimum', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('shipping_country', models.CharField(default='Bangladesh', max_length=100)),
                ('cash_on_delivery', models.BooleanField(default=True)),
                ('sslcommerz_enabled', models.BooleanField(default=True)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('email_from_name', models.CharField(default='WatchStore', max_length=150)),
                ('email_from_email', models.EmailField(default='admin@watchstore.com', max_length=254)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
